use Instagram_DataWarehouse;
GO
IF object_id('bronze.instagram_usage','U') IS NOT NULL
	DROP TABLE bronze.instagram_usage
GO
CREATE TABLE bronze.instagram_usage (
user_id INT,
app_name varchar(20),
age int,
gender varchar(20),
country varchar(30),
urban_rural varchar(20),
income_level varchar(20),
employment_status varchar(30),
education_level nvarchar(50),
relationship_status varchar(30),
has_children varchar(10),
exercise_hours_per_week decimal(5,1),
sleep_hours_per_night decimal(3,1),
diet_quality varchar(20),
smoking varchar(20),
alcohol_frequency varchar(20),
perceived_stress_score int,
self_reported_happiness int,
body_mass_index decimal(4,2),
blood_pressure_systolics int,
blood_pressure_diastolic int,
daily_steps_count int,
weekly_work_hours decimal(5,1),
hobbies_count int,
social_events_per_month int,
books_read_per_year int,
volunteer_hours_per_month decimal(5,1),
travel_frequency_per_year int,
daily_active_minutes_instagram decimal(5,1),
sessions_per_day int,
posts_created_per_week int,
reels_watched_per_day int,
stories_viewed_per_day int,
likes_given_per_day int,
comments_written_per_day int,
dms_sent_per_week int,
dms_received_per_week int,
ads_viewed_per_day int,
ads_clicked_per_day int,
time_on_feed_per_day int,
time_on_explore_per_day int,
time_on_messages_per_day int,
time_on_reels_per_day int,
followers_count int,
following_count int,
uses_premium_features varchar(10),
notification_response_rate decimal(5,2),
account_creation_year int,
last_login_date date,
average_session_length_minutes decimal(5,1),
content_type_preference varchar(20),
preferred_content_theme varchar(20),
privacy_setting_level varchar(20),
two_factor_auth_enabled varchar(20),
biometric_login_used varchar(20),
linked_accounts_count varchar(20),
subscription_status varchar(20),
user_engagement_score decimal(5,2)
);

